

#
# This code was written 2024-12-28 base on code generated by Gemini
#

import os
import serial

if os.name == 'nt':
    port = 'COM6'
else:
    port = '/dev/ttyUSB0'

try:
    ser = serial.Serial(port, 9600)
    print (f"Connectd to port: {port}")

    # serial read/write code codes here

except serial.SerialException as e:
    print (f"Error connecting to serial port: {e}")

finally:

    ser.close()


