

#
# This code was written 2024-12-28 base on code generated by Gemini
#

import os
import serial

if os.name == 'nt':
    port = 'COM6'
else:
    port = '/dev/ttyUSB0'

try:
    ser = serial.Serial(port, 9600)
    
    print (f"Print the current timeout and then set it for 2.0")
    print (f"Serial timeout: {ser.timeout}")
    ser.timeout = 2.0
    print (f"Connectd to port: {port}")
    print (f"Serial info: {ser}")
    print (f"Serial timeout: {ser.timeout}")
    # serial read/write code codes here
    
    input = ser.read (1)

    print (f"Serial read has timed out")
    
except serial.SerialException as e:
    print (f"Error connecting to serial port: {e}")

finally:

    print (f"About to close there serial port")
    
    ser.close()


